version: '3.8'

services:
  flask-app:
    build:
      context: ./demo1/flask-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - flask-app

networks:
  app-network:
    driver: bridge
