name: Docker Image CI

on:
  push:
    branches: ["realcommang"]
  pull_request:
    branches: ["realcommang"]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: docker login -u realcommang -p samsung48

      - name: Build and Push Flask Docker image
        run: |
          docker build -t realcommang/sschat1215-flask:latest -f ./demo1/flask-server/Dockerfile .
          docker push realcommang/sschat1215-flask:latest

      - name: Build and Push React Docker image
        run: |
          docker build -t realcommang/sschat1215-react:latest -f ./Dockerfile .
          docker push realcommang/sschat1215-react:latest
