name: Docker Image CI

on:
  push:
    branches: ["realcommang"]
  pull_request:
    branches: ["realcommang"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t realcommang/sschat1:latest .

      - name: Log in to Docker Hub
        run: docker login -u realcommang -p samsung48

      - name: Push Docker image
        run: |
          docker push realcommang/sschat1215:latest
